version: '3.5'

services:
  service:
    build: .
    ports:
      - 3000:3000
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"